### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by isolud** [isolud/Bjonline_apptest#13]
For ref : crash after player leave a table ( 

stack : 

/node/Blackjack/app.js:1439
        var tbl = tables[tableID].tables[tableIndex].computer_cards;
                                 ^

TypeError: Cannot read property 'tables' of undefined
    at updateComputerCards (/node/Blackjack/app.js:1439:27)
    at computerHit (/node/Blackjack/app.js:1767:2)

)

**Comment by isolud** [comment]
Fixed
